// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue-dark': string;
  'blue-light': string;
  'blue-sea': string;
  'blue-sky': string;
  'coral': string;
  'green-pale': string;
  'grey100': string;
  'grey50': string;
  'grey500': string;
  'moderate-red': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
