// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spacing1': string;
  'spacing2': string;
  'spacing3': string;
  'spacing4': string;
  'spacing5': string;
  'spacing7': string;
  'spacing8': string;
}
export const cssExports: CssExports;
export default cssExports;
