// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bounce': string;
  'box': string;
  'content': string;
  'first': string;
  'icon': string;
  'icons': string;
  'link': string;
  'progresses': string;
  'skills': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
