// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bullets': string;
  'contact': string;
  'item': string;
  'main': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
