// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asks': string;
  'bids': string;
  'book': string;
  'head': string;
  'spread': string;
}
export const cssExports: CssExports;
export default cssExports;
