// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
