// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'hide': string;
  'link': string;
  'menu': string;
  'slide-down': string;
  'slide-up': string;
}
export const cssExports: CssExports;
export default cssExports;
