// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carbon': string;
  'down': string;
  'grey400': string;
  'icon': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
