// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bullet': string;
  'img': string;
}
export const cssExports: CssExports;
export default cssExports;
