// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact': string;
  'hesitate': string;
  'hi': string;
  'item': string;
}
export const cssExports: CssExports;
export default cssExports;
