// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animation': string;
  'bf': string;
  'content': string;
  'fade-in-up': string;
  'hero': string;
  'image': string;
  'item': string;
  'media': string;
  'pp': string;
}
export const cssExports: CssExports;
export default cssExports;
