// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorCard': string;
  'colorContainer': string;
  'hex': string;
  'label': string;
}
export const cssExports: CssExports;
export default cssExports;
