name: Decrypt firebase secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt firebase secrets
        run: ./tools/decrypt.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.PORTOFOLIO }}
